### ISSUE TITLE
Snapfit Disapearing

### ISSUE THREAD

**Issue by fatofthelan** [AlfMikael/snap-generator#8]
Hello, Alf!
I am having an issue where I can create a snapfit, but as soon as I try to drag it into position or adjust it, it vanishes. And after a few time Fusion crashed. Do you think this is unique to my system, or perhaps the add-in requires a change to work with current versions of Fusion?

Thanks for the wonderful add-in! I sure hope it'll continue to work, it's a great piece of work.

**Comment by AlfMikael** [comment]
Hi!

Sorry for the late reply. I am unfamiliar with this specific issue. Two question:
1. Does the part vanish after you have generated the part and clicked "OK" or while you have the dialog window still open?
2. When you say dragging, do you mean moving the joint origin?
